#!/bin/bash

SMALI_VER="1.2.4"

# $1 - filename in (framework folder)
function deodex {
	echo "Deodexing: "$1
	echo "  -> baksmali..."
	`java -Xmx512m -jar baksmali-$SMALI_VER.jar -d deodexed_jar -x ./app/$1`
	`mkdir -p temp`
	echo "  <- smali..."
	`java -jar smali-$SMALI_VER.jar out -o ./temp/classes.dex`

	# filename without extension
	fname=${1%.*}

	# copy apk file to deodexed_apk
	cp ./app/$fname.apk ./deodexed_apk/$fname-step1.apk

	# add temp/classes.dex to apk file
        if [ ! -e ./temp/classes.dex ] 
        then
                echo "Error smile "$fname", no classes.dex file!"
                exit 2
        fi
	7z a -tzip -mx5 ./deodexed_apk/$fname-step1.apk ./temp/classes.dex > /dev/null

	# sign
	`java -classpath $HOME/bin/sign/testsign.jar testsign ./deodexed_apk/$fname-step1.apk ./deodexed_apk/$fname-step2.apk`
	rm ./deodexed_apk/$fname-step1.apk

        # zipalign
        zipalign -f 4 ./deodexed_apk/$fname-step2.apk ./deodexed_apk/$fname.apk
        rm ./deodexed_apk/$fname-step2.apk

	# remove temp folders
	rm -r ./out
	rm -r ./temp
	echo "Deodexed: "$fname".apk"
	rm -f ./app/$fname.odex
	rm -f ./app/$fname.apk
        echo "-----------------------------------------------------"
}


mkdir -p deodexed_apk

#
# Deodexing framework folder
#
#deodex $1

LIST=`find ./app/*.odex`
for ITEM in $LIST
do
    odexfile=${ITEM##*/}
    deodex $odexfile
done
